from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class report_tab(QWidget):
    def __init__(self, repo_name):
        super().__init__()
        self.initUI(repo_name)

    def initUI(self, repo_name):
        self.setObjectName(repo_name + "_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grpStatus = QtWidgets.QGroupBox(self)
        self.grpStatus.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.grpStatus.setObjectName("grpStatus")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.grpStatus)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblStatus = QtWidgets.QLabel(self.grpStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setMinimumSize(QtCore.QSize(50, 0))
        self.lblStatus.setObjectName(repo_name + "_status")
        self.horizontalLayout.addWidget(self.lblStatus)
        self.btnBuild = QtWidgets.QPushButton(self.grpStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBuild.sizePolicy().hasHeightForWidth())
        self.btnBuild.setSizePolicy(sizePolicy)
        self.btnBuild.setObjectName("btnBuild")
        self.horizontalLayout.addWidget(self.btnBuild)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnGetLogs = QtWidgets.QPushButton(self.grpStatus)
        self.btnGetLogs.setObjectName("btnGetLogs")
        self.horizontalLayout.addWidget(self.btnGetLogs)
        self.verticalLayout.addWidget(self.grpStatus)
        self.lblConsoleOutput = QtWidgets.QLabel(self)
        self.lblConsoleOutput.setObjectName("lblConsoleOutput")
        self.verticalLayout.addWidget(self.lblConsoleOutput)
        self.txtConsoleOutput = QtWidgets.QTextEdit(self)
        self.txtConsoleOutput.setObjectName(repo_name + "_log")
        self.verticalLayout.addWidget(self.txtConsoleOutput)
        self.lblStatus.setText("Fail")
        self.grpStatus.setTitle("Статус")
        self.btnGetLogs.setText("Получить логи")
        self.btnBuild.setText("Запустить сборку")
        self.lblConsoleOutput.setText("Логи последней сборки:")
